---
version: 0.2

env:
  variables:
    AWS_REGION: eu-central-1
    ECR_REPOSITORY: commitflow

phases:
  pre_build:
    commands:
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - COMMIT_SHA=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - |
        ACCOUNT_ID=$(aws sts get-caller-identity \
          --query 'Account' --output text)
      - ECR_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY

      - whoami
      - id
      - docker info
      - echo $BUILDAH_ISOLATION
      - |
        aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $ECR_URI
    finally:
      - cat /etc/os-release

  build:
    commands:
      - test -z "$(gofmt -l .)"
      - go vet ./...
      - golangci-lint run
      - yamllint .
      - hadolint Dockerfile

      - docker build -t $ECR_URI:$COMMIT_SHA --format docker .
      - docker tag $ECR_URI:$COMMIT_SHA $ECR_URI:latest
      - docker push $ECR_URI:$COMMIT_SHA
      - docker push $ECR_URI:latest
