---
github_pat: "{{ vault_github_pat }}"
gitlab_pat: "{{ vault_gitlab_pat }}"
postgres_user: postgres
postgres_password: "{{ vault_postgres_password }}"
grafana_user: grafana
grafana_password: "{{ vault_grafana_password }}"
